### ISSUE TITLE
 Feature request: Anonymous messages

### ISSUE THREAD

**Issue by ed-paredes** [bcneng/candebot#129]
It would be nice to have an option to post anonymously for different channels like #hiring-discussions, even create a new #workplace-challenges channel. The idea is that people feel comfortable to express themselves without engaging their current or former coworkers.

**The idea came from another Slack channel.

**Comment by smoya** [comment]
We could use https://opensay.co. They offer BcnEng a free plan.

**Comment by smoya** [comment]
> We could use https://opensay.co. They offer BcnEng a free plan.

This is already in place. OpenSay company sponsors us🚀
