### ISSUE TITLE
Proposal: add field to #hiring-job-board offers with contract type

### ISSUE THREAD

**Issue by alexpdp7** [bcneng/candebot#182]
Many offers, esp. remote offers are for "contractor/freelancer/autónomo/self-employed" positions, because foreign companies without a Spanish legal entity cannot offer regular employee contacts.

Personally, I find this non-ideal, because I'm only interested in regular employee positions, and it makes it very hard to spot them.

I would propose a simple field with "employee" and other options.

**Comment by MeZKaL** [comment]
Proposal:

**In the Form:**
New Field: `contractType`
Possible values: `employee` `contractor`
Validation: Mandtory
Add a Hint: "Regardless of the Contract Type, all positions posted must be permanent/long term"

**In the channel:**
Show it between `location` and `publisher` with the icon 📜 

i.e.:
<img width="1131" alt="image" src="https://github.com/bcneng/candebot/assets/461880/74487b6e-14af-410a-ab70-791e9ddf3006">
