### ISSUE TITLE
Adopt "main" over "master" as the default branch

### ISSUE THREAD

**Issue by ignasi35** [bcneng/candebot#58]
GitHub already provides the tools (I believe they're under _settings_) to rename `master` to `main`.

This change would align with the BcnEng community values.

**Comment by gonzaloserrano** [comment]
ping @smoya to check if we need to change something in netlify's side?

**Comment by smoya** [comment]
No for Candebot (not in Netlify) but maybe in Heroku.

Not in front of the pc until tuesday so I cant really check.

**Comment by ignasi35** [comment]
Is Heroku pulling? If not, it doesn't matter what branch Heroku deploys, it's a private detail an, while it'd bre great Heroku deployed branch was `main` aswell, we can keep that out of scope.

I suggest we change GitHub for the time being and eventually any other place.

**Comment by smoya** [comment]
This has been fixed!
