### ISSUE TITLE
2.5 validation range error message is too long

### ISSUE THREAD

**Issue by smoya** [bcneng/candebot#71]
We should make the error message from https://github.com/bcneng/candebot/blob/master/bot/interact.go#L85-L87 shorter

<img width="495" alt="CleanShot 2021-10-01 at 15 28 26@2x" src="https://user-images.githubusercontent.com/1083296/135628139-5d81bc79-3854-4342-a373-40bc7f79be80.png">

cc @ignasi35 @gonzaloserrano

**Comment by ignasi35** [comment]
Bollocks!
